import React from 'react'
import { z } from 'zod'
import { TaskArea } from './TaskArea.js'
import { TaskStrip } from './TaskStrip.js'
import { dagToneCss } from './task-presentation.js'
import { resumeDriverMessage } from './task-model.js'

export const inject = ['slots', 'remote', 'sessions']
const e = React.createElement
const CSS = `
.ltr-modal-layer{position:absolute;inset:0;z-index:50}.ltr-mask{position:absolute;inset:0;background:rgb(15 23 42 / .26)}
.ltr-modal{position:relative;margin:24px auto;width:min(1160px,calc(100vw - 48px));height:calc(100vh - 48px);overflow:auto;border:1px solid var(--dsw-alias-border-l1);border-radius:16px;background:var(--dsw-alias-bg-base);color:var(--dsw-alias-label-primary);padding:20px;box-shadow:0 20px 60px rgb(15 23 42 / .18)}.ltr-close{float:right}.ltr-btn{display:inline-flex;align-items:center;justify-content:center;gap:4px;height:32px;padding:6px 12px;border:1px solid var(--dsw-alias-border-l2);border-radius:18px;color:var(--dsw-alias-label-primary);background:transparent;font-family:var(--dsw-font-family);font-size:13px;font-weight:400;line-height:20px;white-space:nowrap;cursor:pointer}.ltr-btn:hover:not(:disabled){background:var(--dsw-alias-interactive-bg-hover)}.ltr-btn:disabled{color:var(--dsw-alias-label-dimmed);cursor:not-allowed}.ltr-header-btn{min-width:111px}
.ltr-task-filter{display:flex;align-items:center;gap:8px;margin:16px 0}.ltr-task-filter input,.ltr-task-filter select{padding:8px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;background:var(--dsw-alias-bg-base);color:var(--dsw-alias-label-primary)}.ltr-task-filter input{min-width:260px}.ltr-task-filter .ltr-check{display:inline-flex;align-items:center;gap:4px;white-space:nowrap;font-size:13px}.ltr-task-filter .ltr-check input{min-width:0;margin:0}
.ltr-task-list{display:flex;flex-direction:column;list-style:none;margin:0;padding:0;border-top:1px solid var(--dsw-alias-border-l1)}.ltr-task-list button{display:grid;grid-template-columns:92px minmax(220px,1fr) 170px;gap:12px;align-items:center;width:100%;min-height:54px;padding:10px 4px;border:0;border-bottom:1px solid var(--dsw-alias-border-l1);background:transparent;color:inherit;text-align:left}.ltr-task-list button:hover{background:var(--dsw-alias-interactive-bg-hover)}.ltr-task-list strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:13px}.ltr-task-list small{overflow:hidden;color:var(--dsw-alias-label-tertiary);font-size:12px;text-overflow:ellipsis;white-space:nowrap}.ltr-empty-task-list{margin:0;padding:18px 4px;color:var(--dsw-alias-label-tertiary);font-size:13px}
.ltr-strip{box-sizing:border-box;display:flex;align-items:center;gap:10px;width:calc(100% - var(--dsh-composer-side-clearance) - var(--dsh-composer-side-clearance) - 4 * var(--dsh-composer-dock-inset));max-width:calc(var(--dsh-composer-card-max-width) - 4 * var(--dsh-composer-dock-inset));height:36px;margin:0 auto 8px;padding:4px 5px 4px 12px;border:1px solid var(--dsw-alias-border-l1);border-radius:12px;background:var(--dsw-specific-tip);color:var(--dsw-alias-label-primary)}.ltr-strip-glyph{color:var(--dsw-alias-label-tertiary)}.ltr-strip-label{flex:none;font-size:13px;font-weight:500}.ltr-strip-objective{flex:1;min-width:0;overflow:hidden;padding:0;border:0;background:transparent;color:var(--dsw-alias-label-primary-dimmed);font-size:13px;text-align:left;text-overflow:ellipsis;white-space:nowrap;cursor:pointer}.ltr-strip-progress{flex:0 1 auto;min-width:0;max-width:38%;overflow:hidden;color:var(--dsw-alias-label-tertiary);font-size:12px;text-overflow:ellipsis;white-space:nowrap}.ltr-strip-actions{display:flex;gap:3px}.ltr-icon-button{display:inline-grid;place-items:center;width:28px;height:28px;padding:0;border:0;border-radius:999px;background:transparent;color:var(--dsw-alias-label-tertiary);cursor:pointer}.ltr-icon-button:hover{background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-secondary)}.ltr-icon-button:disabled{opacity:.4;cursor:default}
.ltr-cockpit-header{display:flex;gap:12px;align-items:center;padding-bottom:15px;border-bottom:1px solid var(--dsw-alias-border-l1)}.ltr-cockpit-header>div{flex:1}.ltr-cockpit small{display:block;margin-top:7px;color:var(--dsw-alias-label-tertiary)}.ltr-state{padding:4px 8px;border-radius:99px;font-size:12px}.tone-ongoing{color:var(--dsw-alias-state-business-primary)}.tone-done{color:var(--dsw-alias-state-success-primary)}.tone-warning{color:var(--dsw-alias-state-warning-primary)}.tone-error{color:var(--dsw-alias-state-error-primary)}.tone-muted{color:var(--dsw-alias-label-tertiary)}.tone-neutral{color:var(--dsw-alias-label-secondary)}.tone-selected{color:var(--dsw-alias-label-primary)}.ltr-plan-hint{margin:12px 0;color:var(--dsw-alias-label-tertiary);font-size:12px}
.ltr-cockpit-body{display:grid;grid-template-columns:minmax(0,1fr) 310px;gap:16px;margin-top:16px}.ltr-dag-wrap{min-width:0;border:1px solid var(--dsw-alias-border-l1);border-radius:12px;overflow:hidden}.ltr-dag-tools{display:flex;justify-content:space-between;padding:8px 10px;border-bottom:1px solid var(--dsw-alias-border-l1)}.ltr-dag-tools button{margin-right:6px}.ltr-dag{display:block;width:100%;height:570px;background:var(--dsw-alias-bg-base);touch-action:none}.ltr-edge{fill:none;stroke:var(--dsw-alias-border-l2);stroke-width:2}.ltr-edge.is-selected{stroke:var(--dsw-alias-label-primary);stroke-width:3}.ltr-node rect{fill:var(--dsw-alias-bg-base);stroke:var(--dsw-alias-border-l2);stroke-width:1.5}.ltr-node.tone-done rect{stroke:var(--dsw-alias-state-success-primary)}.ltr-node.tone-error rect{stroke:var(--dsw-alias-state-error-primary)}.ltr-node.tone-warning rect{stroke:var(--dsw-alias-state-warning-primary)}.ltr-node.tone-ongoing rect{stroke:var(--dsw-alias-state-business-primary)}.ltr-node.tone-muted rect{stroke:var(--dsw-alias-label-tertiary);stroke-dasharray:5 4}.ltr-node.is-selected>rect{stroke:var(--dsw-alias-label-primary);stroke-width:2.5}.ltr-node-title,.ltr-node-objective,.ltr-node-state{fill:var(--dsw-alias-label-primary)}.ltr-node-title{font-size:13px;font-weight:600}.ltr-node-objective{font-size:12px}.ltr-node-state{font-size:11px;fill:var(--dsw-alias-label-tertiary)}.ltr-collapse-control rect{fill:var(--dsw-specific-tip);stroke:var(--dsw-alias-border-l2)}.ltr-collapse-control text{fill:var(--dsw-alias-label-secondary);font-size:11px}.ltr-inspector{border:1px solid var(--dsw-alias-border-l1);border-radius:12px;padding:12px}.ltr-inspector ol{padding-left:18px;font-size:12px}.ltr-warning,.ltr-error{color:var(--dsw-alias-state-error-primary)}@media(max-width:800px){.ltr-cockpit-body{grid-template-columns:1fr}.ltr-modal{width:calc(100vw - 20px);height:calc(100vh - 20px);margin:10px}.ltr-dag{height:420px}.ltr-task-list button{grid-template-columns:80px 1fr}.ltr-task-list small{grid-column:2}.ltr-task-filter input{min-width:0;flex:1}}
`
if (typeof document !== 'undefined' && !document.querySelector('style[data-plugin-css="long-task-runtime"]')) { const tag = document.createElement('style'); tag.dataset.pluginCss = 'long-task-runtime'; tag.textContent = CSS; document.head.appendChild(tag) }
if (typeof document !== 'undefined' && !document.querySelector('style[data-plugin-css="long-task-runtime-overrides"]')) { const tag = document.createElement('style'); tag.dataset.pluginCss = 'long-task-runtime-overrides'; tag.textContent = `.ltr-task-list-title{margin:18px 0 8px;font-size:14px}.ltr-task-list-header{display:grid;grid-template-columns:92px minmax(220px,1fr) 170px;gap:12px;padding:0 4px 8px;color:var(--dsw-alias-label-tertiary);font-size:12px}.ltr-node>rect{fill:var(--dsw-alias-bg-base);stroke:var(--dsw-alias-border-l2);stroke-width:1.5}${dagToneCss}@media(max-width:800px){.ltr-task-list-header{grid-template-columns:80px 1fr}.ltr-task-list-header span:last-child{grid-column:2}}`; document.head.appendChild(tag) }
if (typeof document !== 'undefined' && !document.querySelector('style[data-plugin-css="long-task-runtime-collapse-fix"]')) { const tag = document.createElement('style'); tag.dataset.pluginCss = 'long-task-runtime-collapse-fix'; tag.textContent = `.ltr-node.is-selected .ltr-collapse-control rect{stroke:var(--dsw-alias-border-l2);stroke-width:1}.ltr-node.tone-done .ltr-collapse-control rect,.ltr-node.tone-error .ltr-collapse-control rect,.ltr-node.tone-warning .ltr-collapse-control rect{stroke:var(--dsw-alias-border-l2)}`; document.head.appendChild(tag) }
if (typeof document !== 'undefined' && !document.querySelector('style[data-plugin-css="long-task-runtime-controls"]')) { const tag = document.createElement('style'); tag.dataset.pluginCss = 'long-task-runtime-controls'; tag.textContent = `.ltr-dag-legend{display:flex;flex-wrap:wrap;gap:10px;padding:7px 10px;border-bottom:1px solid var(--dsw-alias-border-l1);font-size:11px}.ltr-dag-legend span{display:inline-flex;gap:5px;align-items:center}.ltr-legend-swatch{width:9px;height:9px;border:2px solid currentColor;border-radius:3px}.ltr-goal-edit{display:grid;gap:8px;margin:12px 0;padding:12px;border:1px solid var(--dsw-alias-border-l1);border-radius:10px}.ltr-goal-edit label{display:grid;gap:4px;font-size:12px}.ltr-goal-edit input,.ltr-goal-edit textarea{padding:8px;border:1px solid var(--dsw-alias-border-l2);border-radius:6px;background:var(--dsw-alias-bg-base);color:inherit}.ltr-goal-edit textarea{min-height:64px;resize:vertical}.ltr-event-list{display:grid;gap:8px;padding-left:18px}.ltr-event-list li{display:grid;gap:2px}.ltr-event-list small,.ltr-event-list time{font-size:11px;color:var(--dsw-alias-label-tertiary)}`; document.head.appendChild(tag) }
let opened = false; let selectedTaskId = null; const listeners = new Set(); const notify = () => listeners.forEach(listener => listener()); const openTaskArea = taskId => { selectedTaskId = taskId ?? null; opened = true; notify() }; const closeTaskArea = () => { opened = false; notify() }
function useOpen() { return React.useSyncExternalStore(listener => { listeners.add(listener); return () => listeners.delete(listener) }, () => opened, () => false) }
function HeaderAction() { const open = useOpen(); return e('button', { type: 'button', className: 'ltr-btn ltr-header-btn', onClick: () => open ? closeTaskArea() : openTaskArea() }, '任务区') }
function Overlay({ props, remote, openSession, driveInSession }) { return e(TaskArea, { open: useOpen(), onClose: closeTaskArea, remote, initialTaskId: selectedTaskId, useSessions: props?.useSessions, openSession, driveInSession }) }
function Dock({ useSessions, remote, openSession, driveInSession }) { const sessions = typeof useSessions === 'function' ? useSessions(value => value) : undefined; const id = sessions?.current; const session = id === undefined ? undefined : sessions?.byId?.[id]; return session?.blank === false ? e(TaskStrip, { sessionId: id, remote, onOpen: openTaskArea, openSession, driveInSession }) : null }
const descriptor = (method, schema) => ({ id: `@deepseek-ai/dsh-long-task-runtime#longTasks/${method}`, service: 'longTasks', namespace: 'longTasks', method, invocation: { kind: 'direct' }, parameters: [{ name: 'input', wire: 'input', source: 'json', codec: { mode: 'strict', typeSymbol: method, schema } }], result: { mode: 'strict', typeSymbol: method, schema: z.unknown() } })
const longTaskRemote = { package: '@deepseek-ai/dsh-long-task-runtime', descriptors: [descriptor('listTasks', z.object({ cursor: z.number().optional(), filter: z.object({ state: z.string().optional(), query: z.string().optional(), archived: z.boolean().optional(), sessionId: z.string().optional() }).optional() }).optional()), descriptor('getTask', z.object({ taskId: z.string() })), descriptor('getTaskGraph', z.object({ taskId: z.string(), revision: z.number().optional() })), descriptor('listTaskEvents', z.object({ taskId: z.string(), cursor: z.number().optional(), taskNodeId: z.string().optional() })), descriptor('getCurrentTaskForSession', z.object({ sessionId: z.string() })), descriptor('updateTask', z.object({ taskId: z.string(), expectedRevision: z.number(), action: z.enum(['confirm', 'resume', 'pause', 'cancel']), sessionId: z.string().optional(), workspaceScope: z.string().optional(), recoveryResolution: z.enum(['retry', 'confirmed_succeeded']).optional() })), descriptor('attachCurrentSession', z.object({ taskId: z.string(), sessionId: z.string(), workspaceScope: z.string().optional() })), descriptor('setCurrentSession', z.object({ taskId: z.string(), sessionId: z.string(), workspaceScope: z.string().optional() })), descriptor('clearCurrentSession', z.object({ sessionId: z.string() })), descriptor('rejectReplan', z.object({ taskId: z.string(), expectedRevision: z.number() })), descriptor('editTaskGoal', z.object({ taskId: z.string(), expectedRevision: z.number(), objective: z.string(), reason: z.string(), sessionId: z.string().optional() })), descriptor('acceptReplan', z.object({ taskId: z.string(), expectedRevision: z.number(), sessionId: z.string().optional() })), descriptor('archiveTask', z.object({ taskId: z.string(), expectedRevision: z.number() })), descriptor('restoreTask', z.object({ taskId: z.string() })), descriptor('getTaskNavigation', z.object({ taskId: z.string() }))] }
export async function apply(ctx) { await ctx.remote.$mount(longTaskRemote); const remote = ctx.get('remote.longTasks'); const openSession = sessionId => { ctx.sessions.open(sessionId) }; const driveInSession = async (sessionId, taskId, objective) => { const session = ctx.sessions.binding?.(sessionId)?.session; if (!session || typeof session.prompt !== 'function') return false; const result = await session.prompt([{ type: 'text', text: resumeDriverMessage(taskId, objective) }], 'queue'); return result?.ok === true }; ctx.slots.inject('conversation.session.header.actions', () => ctx.slots.register({ name: 'conversation.session.header.actions', id: 'long-task-header', order: 30, label: '任务区' }, () => e(HeaderAction))); ctx.slots.inject('conversation.input.dock', () => ctx.slots.register({ name: 'conversation.input.dock', id: 'long-task-current', order: 20 }, props => e(Dock, { ...props, remote, openSession, driveInSession }))); ctx.slots.inject('shell.overlay', () => ctx.slots.register({ name: 'shell.overlay', id: 'long-task-overlay', order: 90 }, props => e(Overlay, { props, remote, openSession, driveInSession }))) }
